name: Format Check

on:
  pull_request:
    branches: [develop, main]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install black isort

      - name: Check Black formatting
        run: black --check .

      - name: Check isort import order
        run: isort --check-only .
